.travis.yml, Cargo.lock, Cargo.toml, src/cli.rs, src/commands/keys.rs, src/lib.rs, src/scl_mock.rs
Internal mock SCL API is temporary and to be removed as soon as we have SCL API available for testing.
Resolves #6
=> feat(API): first draft of mock of the SCL API just for testing

Cargo.lock, Cargo.toml, README.md, src/cli.rs, src/lib.rs, src/scl_mock.rs, src/subcommands/keys.rs, src/subcommands/wallet.rs, tests/cli_integration.rs
Todo: 
Fixes #11 and tracking #5
=> Feat wallet transfer

Cargo.lock, Cargo.toml, src/subcommands/auth.rs
=> fix(auth): resolve the user home directory using 'dirs' crate

README.md, src/lib.rs, src/lib_helpers.rs, src/scl_mock.rs, src/subcommands/keys.rs, src/subcommands/wallet.rs
Fixes #41 
Fixes #40 
Fixes #31 
Fixes #42
=> fix(lib): properly handle errors and return informative messages

src/api/fetch.rs, src/api/files.rs, src/api/safe_client_libs.rs, src/api/scl_mock.rs, src/subcommands/cat.rs, src/subcommands/files.rs, tests/cli_cat.rs
=> feat(files): implementation of files sync command reporting add/modified/delete on each file uploaded

src/api/fetch.rs, src/api/files.rs, src/cli.rs, src/subcommands/cat.rs, src/subcommands/helpers.rs, src/subcommands/mod.rs
=> feat(cat): show additional info about native data type of content fetched

.travis.yml, Dockerfile.build, Jenkinsfile, Makefile, tests/common/mod.rs
Hi Josh/Gabriel
Jenkins now provides a build and deployment process for all platforms. Travis has been stripped down to only running Linux.
* In parallel:
- Build Linux in container
- Build Windows
- Build macOS
- Upload build artifacts to S3
For Linux, the container definition is in Dockerfile.build. The use of a .build extension is to differentiate between a container for distributing the application, which we may add at some point in the future.
At this point the time for the Linux build is quite slow. I've got some optimisations I can do for this, but those are mostly infrastructure changes and I'd like to get this merged first.
The deployment process will only occur on the master branch, i.e. after a PR is merged.
* Clone the code with the tags fetched (not done by default)
* …
=> Jenkins Build and Release

.travis.yml, Cargo.toml, src/api/fetch.rs, src/api/files.rs, src/api/safe_client_libs.rs, src/api/scl_mock.rs, src/api/xorurl.rs
=> SCL published seq appendable / immutable integration

src/api/files.rs, tests/cli_files.rs
=> Fix: Handle files with no extension

README.md, src/api/fetch.rs, src/api/files.rs, src/api/safe_client_libs.rs, src/api/scl_mock.rs, src/api/xorurl.rs, src/cli.rs, src/subcommands/files.rs, tests/cli_files.rs
=> test(files): updates to user guide for details about files sync and automated tests for new commands

src/api/fetch.rs, src/api/files.rs, src/api/safe_client_libs.rs, src/api/wallet.rs
Tidies up error mapping in SCL.
=> chore(Errors): SCL integration errors improved

src/api/auth.rs, src/api/errors.rs, src/api/fetch.rs, src/api/files.rs, src/api/helpers.rs, src/api/keys.rs, src/api/mod.rs, src/api/safe_client_libs.rs, src/api/scl_mock.rs, src/api/wallet.rs, src/api/xorurl.rs, src/lib.rs, src/main.rs, tests/cli_wallet.rs
=> feat(lib): lib's custom Error enum to be returned by its API

.travis.yml, Makefile, resources/test-scripts/all-tests, src/api/auth.rs, src/api/fetch.rs, src/api/files.rs, src/api/safe_client_libs.rs, src/api/scl_mock.rs, src/subcommands/auth.rs, src/subcommands/cat.rs, src/subcommands/fake_auth.rs
=> Mock network tests

Cargo.lock, Cargo.toml, README.md, resources/test-scripts/all-tests, src/api/auth.rs, src/api/fetch.rs, src/api/files.rs, src/api/helpers.rs, src/api/keys.rs, src/api/safe_client_libs.rs, src/api/scl_mock.rs, src/api/wallet.rs, src/cli.rs, src/subcommands/helpers.rs, src/subcommands/keys.rs, src/subcommands/wallet.rs, tests/cli_keys.rs, tests/cli_wallet.rs, tests/common/mod.rs
Resolves #23 
Resolves #82 
Resolves #141 
Resolves #158 
This PR also upgrades to latest code from SCL/safe-nd `stable` branches.
=> feat(keys): integration with SCL CoinBalance API

README.md, src/api/fetch.rs, src/api/helpers.rs, src/api/nrs.rs, src/api/wallet.rs, src/cli.rs, src/subcommands/helpers.rs, src/subcommands/keys.rs, src/subcommands/nrs.rs, src/subcommands/wallet.rs, tests/cli_wallet.rs
=> refactor(wallet): make the wallet_insert API to expect only the secret key for the Key to insert

.travis.yml, Cargo.lock, Cargo.toml, Dockerfile.build, resources/test-scripts/all-tests, src/api/fetch.rs, src/api/keys.rs, src/api/nrs.rs, src/api/xorurl.rs, tests/cli_files.rs, tests/cli_nrs.rs
=> Chore ci code quality

src/api/constants.rs, src/api/fetch.rs, src/api/files.rs, src/api/helpers.rs, src/api/keys.rs, src/api/nrs.rs, src/api/wallet.rs, src/api/xorurl.rs, tests/cli_nrs.rs
=> feat(NRS): basic subname creation, and resolution

README.md, src/api/auth.rs, src/api/fake_scl.rs, src/api/files.rs, src/api/keys.rs, src/api/mod.rs, src/api/nrs.rs, src/api/safe_client_libs.rs, src/api/safe_net.rs, src/api/wallet.rs, src/subcommands/mod.rs, src/subcommands/nrs.rs, tests/cli_files.rs, tests/cli_nrs.rs, tests/testfolder/subfolder/subexists.md
This PR not only adds documentation but also a refactor to the internal API we have for our functionality with SAFE Network.
Also, some minor renaming o the `mock` as strictly speaking we have a `fake` instead.
=> doc(readme): add details about NRS commands to User Guide

src/api/constants.rs, src/api/fetch.rs, src/api/files.rs, src/api/mod.rs, src/api/nrs.rs, src/api/nrs_map.rs, src/cli.rs, src/subcommands/nrs.rs, tests/cli_nrs.rs
=> feat(nrs): implementation of nrs remove command

tests/cli_nrs.rs
=> tests(nrs): Add test to check removal of subname

README.md, src/api/files.rs, src/subcommands/cat.rs, tests/cli_files.rs, tests/common/mod.rs
=> fix(files sync): files sync was not committing the changes in FilesContainer when all changes were files removal

Cargo.toml
This is a test release and so will be deleted.
=> Version change : 0.0.1 to 0.0.2

Cargo.toml, Jenkinsfile
Hi Stephen,
As discussed, this checks the 2nd commit for the version change message.
Cheers,
Chris
=> Fix Master Deployment

src/api/wallet.rs
=> refactor(typo): correct a typo in an error message

Cargo.toml
=> Version change : 0.1.0

Cargo.lock, Cargo.toml, README.md, src/subcommands/wallet.rs
=> chore(cli): remove default --feature from Cargo

Dockerfile.build, Jenkinsfile, Makefile, resources/build-cache.sh, src/main.rs, src/subcommands/update.rs
Hi Gabriel/Josh,
This does a dev and 'real' build. The dev versions are linked in the release description. You can see a [release](https://github.com/jacderida/safe-cli/releases/tag/0.0.3) here on my fork.
The dev version uses conditional compilation to disable self update:
```
vagrant@ubuntu-bionic:~$ curl -L -O https://safe-cli.s3.amazonaws.com/safe_cli-0.0.3-x86_64-unknown-linux-gnu-dev.tar
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 13.4M  100 13.4M    0     0  5145k      0  0:00:02  0:00:02 --:--:-- 5143k
vagrant@ubuntu-bionic:~$ tar xvf safe_cli-0.0.3-x86_64-unknown-linux-gnu-dev.tar 
safe
vagrant@ubuntu-bionic:~$ ./safe update
The update command is not supported for the development build.
```
In the …
=> Dev and Release Builds

resources/test-scripts/all-tests
=> tests(CI): Update auth cli builds pulled in

Cargo.lock, Cargo.toml, src/api/fake_scl.rs, src/api/keys.rs, src/api/safe_client_libs.rs, src/api/wallet.rs, tests/cli_wallet.rs, tests/common/mod.rs
=> fix(wallet): add test and check in fake-scl for scenario when transferring 0 amount

Cargo.lock, Cargo.toml, resources/test-scripts/all-tests
=> Version change : 0.2.2

Cargo.lock, Cargo.toml, src/api/fetch.rs, src/api/files.rs, src/api/helpers.rs, src/api/keys.rs, src/api/mod.rs, src/api/nrs.rs, src/api/wallet.rs, src/api/xorurl.rs, src/api/xorurl_media_types.rs, src/subcommands/cat.rs, tests/cli_cat.rs
Resolves #240 
Resolves #213 
Fixes #238
=> feat(xorurl): allow to encode media-type in XOR-URLs for ImmutableData files

src/api/files.rs, src/subcommands/files.rs, src/subcommands/helpers.rs, src/subcommands/nrs.rs
Fixes #249 
This includes a minor change to nrs cmd help menu and args as suggested here: https://safenetforum.org/t/new-release-vault-phase-1-real-vault/29712/184
=> fix(files): report an error when adding a file with same name as existing one on target

README.md, safe-api/src/api/files.rs, safe-api/src/api/keys.rs, safe-api/src/api/wallet.rs, safe-cli/subcommands/wallet.rs, safe-cli/tests/cli_keys.rs, safe-cli/tests/cli_wallet.rs, safe-cli/tests/common/mod.rs, safe-ffi/ffi/wallet.rs
=> feat(wallet): support to specify a specific Wallet speandable balance as source/destination

Cargo.lock, Makefile, safe-api/src/api/files.rs, safe-api/src/api/nrs.rs, safe-api/src/api/wallet.rs, safe-cli/tests/cli_wallet.rs, safe-ffi/ffi/nrs.rs
=> fix(wallet): make sure we use the path when using Wallet NRS URLs in transfer operations

Cargo.lock, README.md, resources/test-scripts/all-tests, safe-api/src/api/fetch.rs, safe-cli/cli.rs, safe-cli/subcommands/cat.rs, safe-cli/subcommands/dog.rs, safe-cli/subcommands/mod.rs, safe-cli/tests/cli_cat.rs, safe-cli/tests/cli_dog.rs, safe-cli/tests/common/mod.rs, safe-ffi/Cargo.toml, safe-ffi/build.rs, safe-ffi/ffi/fetch.rs, safe-ffi/ffi/ffi_structs.rs
=> feat(cli): new dog command to inspect content retrieving only metadata

Makefile
Changes a container reference so we can do another release with a publish this time.
=> Version change: 0.5.0

Dockerfile.android.armv7.build, Dockerfile.android.x86_64.build
---
Provide QA team and reviewer steps to test the resolution.
For example:
```
QA:
Easiest way to test this PR would be to:
- Run safe-auth cli client in a different terminal
- login
- safe wallet insert <problem link>
- Expect to see an authentication error output
```
---
Commit messages should conform to the format:
```
<type>(<scope>): <description>
[optional body]
```
For example:
```
fix(auth): proper values returned on auth_decode_ipc_msg errors
- Test case for authenticator error -208 IncompatibleMockStatus
- Test case for authenticator error -103 when decoding share MData
request for non-existent MData
```
Commit `type` can be one of:
**feat**: New feature
**fix**: Bug fix
**docs**: Documentation only changes
**style**: Changes that do not affect the meaning of the code …
=> Remove openssl requirements from android builds

Cargo.lock, safe-api/Cargo.toml, safe-ffi/Cargo.toml, safe-ffi/ffi/fetch.rs, safe-ffi/ffi/ffi_structs.rs, safe-ffi/ffi/files.rs, safe-ffi/ffi/helpers.rs, safe-ffi/ffi/keys.rs, safe-ffi/ffi/mod.rs, safe-ffi/ffi/nrs.rs, safe-ffi/ffi/wallet.rs, safe-ffi/ffi/xorurl.rs
=> refactor(ffi): update ffi_utils crate to 0.13.0 and use new vec and string methods

Cargo.lock, safe-cli/Cargo.toml, safe-cli/subcommands/auth.rs
=> fix(cli): fix issue 203 storing credentials onto XDG_DATA_HOME based path

safe-api/src/api/files.rs
=> fix(api): use type tag decoded from xorurl when fetching a FilesContainer

safe-ffi/ffi/fetch.rs, safe-ffi/ffi/ffi_structs.rs
=> Use empty string instead of null ptr and add parameter names for the fetch and inspect FFI callbacks

Jenkinsfile
These downstream jobs were renamed but this reference wasn't updated.
=> fix(ci): use correct job references

safe-ffi/build.rs
=> chore(ffi): generate C language bindings for safe-ffi

safe-ffi/build.rs, safe-ffi/ffi/ffi_structs.rs, safe-ffi/ffi/nrs.rs
=> chore(ffi): use new XorUrlEncoder instead of null ptr in parse_and_resolve_url

safe-api/src/api/constants.rs, safe-api/src/api/fetch.rs, safe-api/src/api/files.rs, safe-api/src/api/keys.rs, safe-api/src/api/mod.rs, safe-api/src/api/nrs.rs, safe-api/src/api/safe_client_libs.rs, safe-api/src/api/wallet.rs, safe-api/src/api/xorurl.rs, safe-cli/cli.rs, safe-cli/shell.rs, safe-cli/tests/cli_nrs.rs, safe-ffi/ffi/fetch.rs, safe-ffi/ffi/ffi_structs.rs, safe-ffi/ffi/files.rs, safe-ffi/ffi/helpers.rs, safe-ffi/ffi/keys.rs, safe-ffi/ffi/mod.rs, safe-ffi/ffi/nrs.rs, safe-ffi/ffi/wallet.rs, safe-ffi/ffi/xorurl.rs
=> refactor(api): define an enum for the XOR URL base encoding parameter

Cargo.lock, safe-api/src/api/authenticator.rs, safe-authd/requests/log_in.rs
=> fix(api): provide more descriptive error messages for login/create_acc APIs

safe-cli/README.md
Just a little addition to the user guide.
=> Added instructions re fetching binary files, with or without --hexdump

safe-cli/subcommands/files.rs, safe-cli/subcommands/nrs.rs
tiny fix of error message text.
=> fix(cli): files and nrs subcommand help text referred to keys subcommand

resources/notarize.sh
=> fix(mac): remove hardened runtime for catalina

.github/workflows/master.yml, .github/workflows/pr.yml, Makefile, resources/get_release_description.sh
Collection of little improvements, none of these are strictly needed.
=> chore/ci: make GitHub Actions improvements

.github/workflows/master.yml, Makefile
=> build and upload dev native libs for FFI on master branch

.github/workflows/master.yml
=> fix(ci): update deploy file name

.github/workflows/master.yml, .github/workflows/pr.yml, Cargo.lock, Makefile, resources/build-component.sh, resources/test-scripts/api-tests, resources/test-scripts/cli-tests, safe-api/Cargo.toml, safe-cli/Cargo.toml, safe-ffi/Cargo.toml
+ Remove some unneeded stuff
+ Add iOS builds back into PR workflow
=> chore(ci): update GHA

.github/workflows/master.yml, Makefile, resources/package-deploy-artifacts.sh
=> chore(ci): pack and upload dev ffi zips

.github/workflows/master.yml, .github/workflows/pr.yml
=> chore(CI): simplify iOS build using cargo-lipo

Cargo.lock, safe-api/Cargo.toml, safe-api/src/api/auth.rs, safe-api/src/api/authenticator.rs, safe-api/src/api/errors.rs, safe-api/src/api/fake_scl.rs, safe-api/src/api/fetch.rs, safe-api/src/api/files.rs, safe-api/src/api/helpers.rs, safe-api/src/api/nrs.rs, safe-api/src/api/safe_client_libs.rs, safe-api/src/api/safe_net.rs, safe-cli/README.md, safe-cli/cli.rs, safe-cli/subcommands/files.rs, safe-cli/subcommands/helpers.rs, safe-cli/subcommands/mod.rs, safe-cli/subcommands/xorurl.rs, safe-cli/tests/cli_files.rs, safe-cli/tests/cli_xorurl.rs, safe-ffi/ffi/errors.rs, safe-ffi/ffi/files.rs
=> feat(files): expand dry-run to files xorurl and expose top level command for convenience

.github/workflows/master.yml
See https://github.com/maidsafe/safe_client_libs/issues/1108
=> chore/ci: update deprecated AWS action

.github/workflows/master.yml
=> chore(ci): notarize macos FFI libs

.github/workflows/master.yml, Cargo.lock, safe-cli/operations/auth_daemon.rs
=> fix(cli): make sure target installation path exists before installing authd

safe-api/src/api/fake_scl.rs, safe-api/src/api/fetch.rs, safe-api/src/api/helpers.rs, safe-api/src/api/safe_client_libs.rs
=> Use available random functions instead of custom ones

Cargo.lock, safe-api/src/api/authd_client_api.rs, safe-api/src/api/safe_client_libs.rs, safe-api/src/api/wallet.rs, safe-api/src/api/xorurl.rs, safe-authd/main.rs, safe-authd/requests/status.rs, safe-cli/Cargo.toml, safe-cli/README.md, safe-cli/cli.rs, safe-cli/operations/auth_daemon.rs, safe-cli/subcommands/mod.rs, safe-cli/subcommands/xorurl.rs, safe-cli/tests/cli_xorurl.rs, safe-cli/tests/common/mod.rs
Fixes #396 
Fixes #406 
This PR also implements the addition of authd version on the status report:
```
$ safe auth status
Sending request to authd to obtain an status report...
+------------------------------------------+-------+
| SAFE Authenticator status                |       |
+------------------------------------------+-------+
| Authenticator daemon version             | 0.0.2 |
+------------------------------------------+-------+
| Logged in to a SAFE account?             | false |
+------------------------------------------+-------+
| Number of pending authorisation requests | 0     |
+------------------------------------------+-------+
| Number of notifications subscribers      | 0     |
+------------------------------------------+-------+
```
=> feat(cli): xorurl decode command

safe-api/src/api/fetch.rs, safe-api/src/api/mod.rs, safe-cli/README.md, safe-cli/subcommands/auth.rs, safe-cli/subcommands/files.rs, safe-cli/tests/cli_files.rs, safe-cli/tests/common/mod.rs
=> feat(cli): add files ls command

.github/workflows/master.yml, resources/get_release_description.sh
Also fix release notes generation script to properly set authd Windows binary checksums.
=> fix(ci): publish dev libs to S3 needed for mobile testing

safe-api/src/api/fake_scl.rs, safe-api/src/api/files.rs, testdata/.subhidden/hiddensub.md, testdata/.subhidden/test.md
=> feat(files): use file's xorurl to decide if it needs to be re-uploaded in a files sync operation

safe-api/src/api/app/files.rs, safe-cli/README.md, safe-cli/subcommands/files.rs, safe-cli/subcommands/vault.rs
=> feat/files: API and CLI command to remove a file or path from a FilesContainer

safe-authd/main.rs, safe-authd/operations.rs, safe-authd/operations_win.rs
Note we still don't have logs out from authd on Windows platform.
=> feat/authd: change default authd log dir from /tmp to ~/.safe/authd/logs

safe-api/src/api/app/fake_scl.rs, safe-api/src/api/app/fetch.rs, safe-api/src/api/app/files.rs, safe-api/src/api/app/safe_client_libs.rs, safe-api/src/api/app/safe_net.rs, safe-cli/subcommands/cat.rs, safe-cli/subcommands/dog.rs, safe-cli/tests/cli_cat.rs, safe-ffi/build.rs, safe-ffi/ffi/constants.rs, safe-ffi/ffi/fetch.rs, safe-ffi/ffi/files.rs, safe-ffi/ffi/mod.rs
depends on https://github.com/maidsafe/safe_client_libs/pull/1169
=> feat(api): add range based request for the immutable data

.github/workflows/master.yml, .github/workflows/pr.yml, Cargo.lock, jsonrpc-quic/Cargo.toml, safe-api/Cargo.toml, safe-api/src/api/app/files.rs, safe-api/src/api/app/safe_client_libs.rs, safe-authd/Cargo.toml, safe-authd/operations_win.rs, safe-cli/operations/auth_and_connect.rs, safe-cli/operations/auth_daemon.rs, safe-cli/subcommands/files.rs, safe-cli/subcommands/keys.rs, safe-cli/subcommands/wallet.rs, safe-cli/tests/cli_cat.rs, safe-ffi/Cargo.toml
=> fix(ffi): use baby-fleming-mobile scl and enable mobile CI builds

.github/workflows/master.yml
=> chore(cli): upload Android and iOS libs to S3

CHANGELOG.md, Cargo.lock, safe-api/Cargo.toml
=> Version change: safe-api-v0.10.1

.github/workflows/master.yml, Cargo.lock, safe-authd/Cargo.toml, safe-ffi/Cargo.toml
=> Api bump 0.10.1

Cargo.lock, safe-cli/operations/auth_and_connect.rs, safe-cli/operations/vault.rs, safe-cli/subcommands/vault.rs
depends on: https://github.com/maidsafe/safe-network-launch-tool/pull/10
=> Add ip option when launching a new local network

safe-ffi/ffi/files.rs
=> feat/ffi: add files_contains_remove_path API

Cargo.lock, jsonrpc-quic/Cargo.toml, jsonrpc-quic/client_endpoint.rs, jsonrpc-quic/server_endpoint.rs, jsonrpc-quic/utils.rs, safe-api/src/api/authd_client/notifs_endpoint.rs, safe-api/src/api/common.rs, safe-authd/Cargo.toml, safe-authd/authd.rs, safe-authd/notifs.rs, safe-authd/operations_win.rs
=> chore(deps): update to use latest scl and quinn 0.6.0

.github/workflows/master.yml, .github/workflows/pr.yml, safe-ffi/Cargo.toml
=> chore/ci: enable mobile ci builds

.github/workflows/pr.yml, .gitignore, Cargo.lock, resources/test-scripts/install-vault-and-authd, resources/test-scripts/run-vault-and-authd, safe-authd/operations_win.rs, safe-cli/Cargo.toml, safe-cli/README.md, safe-cli/benches/keys.rs, safe-cli/benches/small-put.rs, safe-cli/operations/vault.rs, safe-cli/subcommands/vault.rs
=> Add simple benchmark and `run-baby-fleming -t` for easy network setup and login

safe-cli/operations/config.rs
=> fix/cli: create folder for storing network conn info if path doesn't exist

safe-cli/Cargo.toml, safe-cli/operations/auth_and_connect.rs
=> fix/cli: info and warning about missing/invalid credentials are now being logged rather than sent to stdout

Cargo.lock, safe-api/src/api/app/xorurl.rs, safe-api/src/api/authd_client/authd_client_api.rs, safe-cli/operations/auth_daemon.rs, safe-cli/subcommands/auth.rs
=> refactor/api: remove authd client install/uninstall APIs and auth uninstall cmd from CLI

Cargo.lock, safe-ffi/Cargo.toml, safe-ffi/ffi/ffi_structs.rs, safe-ffi/ffi/helpers.rs, safe-ffi/ffi/xorurl.rs
**Testing status with C# APIs:**
**Completed**
* Windows
* MacOS
* iOS
* Android
* Linux
=> FFI: refactor XorUrlEncoder and expose subnames field as string list instead of json string

.github/workflows/benchmark.yml, .github/workflows/network-test.yml
This should stop logging running indefinitely and speed up failure notifications
=> ci(testnet): stop testnet when tests failed.

safe-ffi/ffi/fetch.rs
=> fix(ffi): ffi panic fix when media_type has no value

safe-api/src/api/app/xorurl.rs, safe-ffi/ffi/ffi_structs.rs, safe-ffi/ffi/nrs.rs, safe-ffi/ffi/xorurl.rs
=> Update FFI to latest SafeUrl and Inspect API changes

safe-ffi/ffi/fetch.rs, safe-ffi/ffi/ffi_structs.rs
=> fix(ffi): return null when value is None

safe-ffi/ffi/files.rs
=> chore(ffi): refactor files API to return FilesMap object

safe-cli/tests/cli_files_get.rs
Only the tests were broken on windows, not the code under test.
=> fix(cli): fixes some 'files get' tests that were failing on windows due to path issues

.github/workflows/benchmark.yml, .github/workflows/network-test.yml, safe-api/src/api/app/xorurl.rs
Update cli directory in CI from `$HOME/.safe/safe-cli` to `$HOME/.safe/cli` - this brings it in line with where the cli binary is installed when the install script is run
=> chore(ci): update cli directory to correct dir

Cargo.lock, jsonrpc-quic/Cargo.toml, safe-api/Cargo.toml, safe-authd/Cargo.toml, safe-cli/Cargo.toml, safe-cmd-test-utilities/Cargo.toml, safe-ffi/Cargo.toml
=> refactor(deps): standardise cargo dependency versioning

Makefile, safe-ffi/ffi/fetch.rs, safe-ffi/ffi/ffi_structs.rs, safe-ffi/ffi/mod.rs, safe-ffi/ffi/sequence.rs, safe-ffi/lib.rs
=> feat/ffi: expose sequence data APIs from the ffi

sn_cli/README.md
=> chore(deps): update to reference renamed sn_app

.github/workflows/benchmark.yml, .github/workflows/network-test.yml, .github/workflows/pr.yml, .gitignore, resources/get_release_description.sh, resources/test-scripts/api-mock-tests, resources/test-scripts/cli-mock-tests, sn_api/src/api/app/fake_scl.rs, sn_cli/README.md, sn_cli/cli.rs, sn_cli/operations/config.rs, sn_cli/operations/mod.rs, sn_cli/operations/node.rs, sn_cli/shell.rs, sn_cli/subcommands/mod.rs, sn_cli/subcommands/node.rs
Expecting 3 clippy errors to show up in CI - these are pre-existing issues unrelated to the changes made in this PR
=> chore(node): update to reference renamed sn_node crate/repo

sn_cli/README.md
=> docs: add notes for sn_fs

sn_api/src/api/app/safe_client.rs
=> fix(api): remove repeated data storing in SafeAppClient::store_sequence()

sn_api/src/api/app/mod.rs, sn_api/src/api/app/safe_client.rs, sn_api/src/api/app/sequence.rs
=> Fix seq append

sn_api/Cargo.toml, sn_api/src/api/authenticator/mod.rs
=> feat:check for existing balance + err when creating acct

resources/get_release_description.sh, sn_api/src/api/app/wallet.rs, sn_api/src/api/authenticator/mod.rs, sn_api/src/api/common.rs, sn_authd/README.md, sn_cli/README.md, sn_cli/operations/auth_daemon.rs, sn_cli/subcommands/keys.rs, sn_cli/subcommands/networks.rs, sn_cli/subcommands/wallet.rs
=> doc(UserGuide): updates and enhancements to the User Guide, and to some commands help messages

Cargo.lock, sn_cli/Cargo.toml, sn_cli/operations/node.rs, sn_cli/subcommands/node.rs, sn_cli/subcommands/update.rs
Also, changing the default number of nodes launched by `node run-baby-fleming` command to 11.
=> fix(cli): CLI update command was looking up in the wrong URL

qjsonrpc/client_endpoint.rs, qjsonrpc/server_endpoint.rs
Resolves #685 
Refactors the parameters to `qjsonrpc` `ClientEndpoint` and `ServerEndpoint` constructors to be more generic without changing the current interface.
=> refactor: makes path parameters generic for qjsonrpc Enpoint ctor

CHANGELOG.md, Cargo.lock, qjsonrpc/Cargo.toml, sn_authd/Cargo.toml, sn_cli/Cargo.toml
=> chore: update launch tool dep

sn_api/src/api/app/nrs.rs
This fixes the following problem
```sh
$ safe files put /tmp/data.bin
$ safe nrs create --link <filescontainer>?v=0 my/nrs/name
$ safe cat safe://my/nrs/name/data.bin
```
Note that backslash throws an error as expected: "Problem parsing the URL ... invalid domain character"
Possibly this (and the existing check for the space character that comes just before it) should reside in [validate_nrs_name](https://github.com/maidsafe/sn_api/blob/2dff02dc71bc3574763906c8592d32bde64337c9/sn_api/src/api/app/nrs.rs#L301)? For now keeping all this logic together seems most sensible.
=> Invalidate public names containing slash char

sn_cli/operations/auth_daemon.rs
Don't even try to read Safe credentials from environment variables when the --config option is specified, since --config has priority and even if it was set but one of the env vars was set the command will fail.
=> refactor(cli): don't attempt to read authd credentials from env vars if --config was passed

CHANGELOG.md, qjsonrpc/Cargo.toml, sn_api/Cargo.toml, sn_authd/Cargo.toml, sn_cli/Cargo.toml
=> Version change: sn_api-v0.19.0; sn_cli-v0.19.0; sn_authd-v0.1.1; qjsonrpc-v0.1.1

Cargo.lock, qjsonrpc/Cargo.toml, sn_api/Cargo.toml, sn_api/src/api/app/test_helpers.rs, sn_api/src/api/authd_client/notifs_endpoint.rs, sn_api/src/api/common.rs, sn_authd/Cargo.toml, sn_authd/notifs.rs, sn_authd/requests/allow.rs, sn_authd/requests/deny.rs, sn_cli/Cargo.toml
=> chore(tokio): upgrade tokio to v1.3.0

CHANGELOG.md, Cargo.lock, sn_api/Cargo.toml, sn_authd/Cargo.toml, sn_cli/Cargo.toml
=> Version change: sn_api v0.23.2; sn_cli v0.23.2; sn_authd v0.5.2

CHANGELOG.md, Cargo.lock, sn_api/Cargo.toml, sn_authd/Cargo.toml, sn_cli/Cargo.toml
=> Version change: sn_api v0.25.0; sn_cli v0.25.0; sn_authd v0.7.0

CHANGELOG.md, Cargo.lock, sn_api/Cargo.toml, sn_api/src/api/errors.rs, sn_authd/Cargo.toml, sn_cli/Cargo.toml
=> Add feature gate for app error and version change

CHANGELOG.md, Cargo.lock, sn_api/Cargo.toml, sn_api/src/api/app/safe_client.rs, sn_authd/Cargo.toml, sn_cli/Cargo.toml
=> Update sn_client and release new version

Cargo.lock
=> Update sn_client and sn_messaging

resources/install.sh
=> fix: install script now uses prebuild latest-package

CHANGELOG.md, Cargo.toml
BREAKING CHANGE: updating to latest sn_client
=> refactor(deps): update to latest sn_client

README.md
BREAKING CHANGE: previous commit should have been a breaking change
but commit msg got lost in a rebase
=> chore: add breaking_change commit

Cargo.toml
=> fix: tie tokio to 1.6 for stability

src/app/multimap.rs
BREAKING CHANGE: Multimap entries will be assigned a different data type when they are created.
In the same way the xorurls for files and serialized files containers needed to have the correct data type specified as a spot or a blob, so too did entries for multimaps that get used as part of the NRS system.
As per files, if the multimap entry is less than 3072 bytes, it'll be stored as a spot, otherwise, it'll be stored as a blob.
With this change, all the CLI tests that weren't already ignored before recent changes, are now passing.
=> fix: use correct data type on multimap entries
