maidsafe/sn_api

- src/cli.rs
- src/lib.rs
- src/lib_helpers.rs
- src/subcommands/keys.rs
Also allow base32 (default) and base32z encoding to be chosen by the user, e.g.:
```
$ safe keys create --test-coins --xor-url base32z
Note that the Key to be created will be preloaded with **test coins** rather than real coins
You must pass a preload amount with test-coins, 1000.111 will be added
New Key created at XOR-URL: "safe://hbkwmnbefby6w8dzqkenwh9imryt4nnck47uy7dggzjqnyozgwgdpqamz4"
Key pair generated: pk="a0a107a871ddca40a9cfd564047421315aecc1d198d74b84085cd430daec2efadd29f1fdf81ac16e1671980e7b3232f4", sk="f90bcb6e386fc7c3dc3e8a40f2dd1a677670d975be30fb05429bd4cb1101ba3a"
```
If the provided base is not supported is uses the default:
```
$ cargo run -- keys create --test-coins --xorurl base64
Note that the Key to be created will be preloaded with **test coins** rather than real …
```
> feat(xor-url): add support for XOR-URL using CID

- .travis.yml
- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/lib.rs
- src/lib_helpers.rs
- src/scl_mock.rs
- src/subcommands/auth.rs
- src/subcommands/helpers.rs
- src/subcommands/keys.rs
- src/subcommands/mod.rs
- src/subcommands/wallet.rs
- tests/cli_integration.rs
Resolves #7 
Fixes #30 
Fixes #31 
This PR implements:
- The `auth` command which generates auth request and sends it to the safe_auth CLI daemon, storign the response in `~/.safe/credentials`
- The `auth clear` command which clears the content of `~/.safe/credentials`
- It uses the credentials from `~/.safe/credentials` to connect to the network preluding the handling of any command like `keys` or `wallet` which need the `safe_app` instance connected to the network for the operations
> feat(cli): implementation of auth command to get authorisation from SAFE Authenticator

- README.md
- src/api/files.rs
- src/api/safe_client_libs.rs
- src/api/scl_mock.rs
- src/api/wallet.rs
- src/subcommands/files.rs
Fixes #110 
Fixes #121 
Fixes #122 
Also, with this PR errors for individual files are included in the report with "E" sign, e.g.:
```
$ safe files put -r ./tests/testfolder
FilesContainer created at: "safe://hbyz6myh9bcqtpo5y8c1yxenctk8us899kmck8c1mw3badcuazxqfhrj5w"
+  ./tests/testfolder/another.md              safe://hoqc91w6uyj8fq8yj5xaaa549zj7zsqf56jsbo6nfafsd4acx7boaq 
+  ./tests/testfolder/noextension             safe://hoxxtw4cb9zgh9owhoepcmr7foo1jh9rqagagemo3i77i6g5hckecc 
E  ./tests/testfolder/nopermissions           <Failed to read file from local location: Permission denied (os error 13)> 
+  ./tests/testfolder/subfolder/subexists.md  safe://hox749but6yinunqdzsetk17zhf4gqhuaj7o3iojjsd3qgarm3r51m 
+  ./tests/testfolder/test.md …
```
> refactor(files): enhancements to error messages and to how errors are reported for files

- Dockerfile.build
Hi Gabriel/Josh,
This synchronises the IDs with the IDs of the `jenkins` user on the build slave. This should hopefully reduce the Linux build time quite significantly, because it avoids having to change permissions for thousands of files (this is a classic problem with Docker - details [here](https://boxboat.com/2017/07/25/fixuid-change-docker-container-uid-gid/) if you're interested). The external disks used by machines on AWS are quite slow, so changing all the permissions can take 5 - 10 minutes sometimes.
Once this is merged I can regenerate the slave with the updated container.
Cheers,
Chris
> Update Container IDs

- README.md
- src/api/fetch.rs
- src/api/files.rs
- src/subcommands/files.rs
- tests/cli_files.rs
Trailing slash in source and destination paths are now taken into account to realise the final destination path, both for files put and sync commands.
Fixes #134
> fix(files): remove --set-root arg in favor of using source and dest args

- Jenkinsfile
- Makefile
- README.md
- resources/test-scripts/all-tests
- src/api/auth.rs
- src/api/fetch.rs
- src/api/files.rs
- src/api/scl_mock.rs
- src/cli.rs
- src/subcommands/auth.rs
- src/subcommands/container.rs
- src/subcommands/fake_auth.rs
- src/subcommands/files.rs
- src/subcommands/mod.rs
Resolves #157 
This PR also:
- Implements an additional feature to allow the user to set the port number where the authorisation request shall be sent to with `$ safe auth --port <port number>` command.
- Implements the `--dry-run` feature for the `files put` and `files sync` commands
- Runs the safe_auth service in at a random port each time for tests
> feat(files): allow files sync --delete only with --recursive

- Jenkinsfile
Changes the build to use the project specific slave rather than the generic slave.
This slave has the updated container on it.
> Use Project Specific Slave

- resources/test-scripts/all-tests
- src/api/fetch.rs
- src/api/files.rs
- src/api/keys.rs
- src/api/mod.rs
- src/api/nrs.rs
- src/api/wallet.rs
- src/api/xorurl.rs
- src/subcommands/cat.rs
> feat(xorurl): use one byte to encode SAFE native data type, and another two bytes for the content type info

- .gitignore
- Cargo.lock
- Cargo.toml
- Jenkinsfile
- Makefile
- README.md
- resources/test-scripts/all-tests
- src/cli.rs
- src/main.rs
- src/subcommands/mod.rs
- src/subcommands/update.rs
Hi Gabriel/Josh/Stephen,
This uses the [self_update](https://crates.io/crates/self_update) crate to pull in new releases from GitHub.
On my fork there are a couple of [releases](https://github.com/jacderida/safe-cli/releases). On this branch I've reverted the version change commits I used to produce them.
At this point in time, only version 0.0.1 was available on GitHub.
Here is the output from running version 0.0.1:
```
vagrant@ubuntu-bionic:~$ ./safe update
Checking target-arch... x86_64-unknown-linux-gnu
Checking current version... v0.0.1
Checking latest released version... v0.0.1
Update status: `0.0.1`!
```
Version 0.0.2 was then uploaded to GitHub.
File size before the update:
```
vagrant@ubuntu-bionic:~$ ll
<some output snipped>
-rwxr-xr-x 1 vagrant vagrant 14466744 Jul 25 14:08 …
```
> Self Update

- Jenkinsfile
It turns out we can use the --no-merges option to remove the merge
related commits. This is a much nicer solution.
> chore/ci: filter commits for deployment

- resources/test-scripts/all-tests
Rather than recompile the authenticator we can pull the nightly release and run that.
> Use Nightly Build for Safe Auth

- README.md
- src/api/fake_scl.rs
- src/api/fetch.rs
- src/api/files.rs
- src/api/helpers.rs
- src/api/keys.rs
- src/api/mod.rs
- src/api/nrs.rs
- src/api/nrs_map.rs
- src/api/safe_client_libs.rs
- src/api/wallet.rs
- src/api/xorurl.rs
- src/cli.rs
- src/subcommands/cat.rs
- src/subcommands/files.rs
- src/subcommands/keys.rs
- src/subcommands/wallet.rs
- tests/cli_cat.rs
- tests/cli_files.rs
- tests/cli_keys.rs
- tests/cli_nrs.rs
- tests/common/mod.rs
- Add a validation to files and nrs commands and APIs, to make sure NRS name provided to nrs create/add, as well as target URL provided to files sync commands are unversioned
- Implementation of an additional level for the `--info` argument in the `cat` command to display the content of the NRS map, e.g.:
```
Resolved using NRS Map:
PublicName: "mypubname"
Container XOR-URL: safe://hnyydyiec84yks653p87zycggzyh691a8y49n5n7srh4awjpzaayhfgnunbqh
Native data type: PublishedSeqAppendOnlyData
Type tag: 1500
XOR name: 0x50c3e80ab7b7969fb7030c6b839efcb0706be2d8bb627358a25b7c601c298531
Version: 4
+------------------------+----------------------+----------------------+--------------------------------------------------------------------------+
| NRS name/subname       | Created              | …
```
>  feat(cat): implement an additional level for --info to cat command, plus additional validations to files and nrs commands

- Jenkinsfile
- Makefile
- resources/get_release_description.sh
- resources/safe_completion.sh
Hi Gabriel,
This is mainly related to user feedback and a couple of other things:
* Do a full clean build as opposed to using a cache when we're building `master` 
* Run `strip` against the release artifacts
* Distribute with zips rather than tars
* Automatically add sha-256 checksums for the release builds
* Add the community contributed safe_completion.sh as a release asset and provide some instructions in the description for setting it up
[Here](https://github.com/jacderida/safe-cli/releases/tag/0.2.3) is a new example release on my fork.
Cheers,
Chris
> Release Process Issues and Community Feedback

- Makefile
- resources/get_release_description.sh
Adds a set of tar.gz assets and fixes another couple of little things.
[Example](https://github.com/jacderida/safe-cli/releases/tag/0.2.3) release on my fork.
Cheers,
Chris
> Produce tar.gz Assets

- resources/build-cache.sh
These tests were failing during the Docker build job, but we don't really actually need to run the tests in this context.
> chore(ci): remove running tests in docker build

- safe-api/src/api/fake_scl.rs
- safe-api/src/api/fetch.rs
- safe-api/src/api/files.rs
- safe-api/src/api/keys.rs
- safe-api/src/api/nrs.rs
- safe-api/src/api/safe_client_libs.rs
- safe-api/src/api/wallet.rs
- safe-api/src/api/xorurl.rs
Benefits of doing this:
- It is idiomatic for unit tests to go into a `#[cfg(test)]`-gated `tests`
module.
- This results in better organization of the code.
- Unit tests are not built along with regular code when running `cargo
build` (not sure if this is true for functions marked `#[test]`)
> refactor/test: move unit tests to `tests` modules

- safe-api/src/api/errors.rs
- safe-api/src/api/fetch.rs
- safe-cli/subcommands/dog.rs
- safe-ffi/ffi/fetch.rs
This adds a new `inspect` API, and the CLI `dog` command is simply switched to make use of it instead of using `fetch` API.
> feat(fetch): add a new API which allows to inspect a safe URL without retrieving the actual content

- Jenkinsfile
These were mistakenly renamed in a refactor.
> Version change: 0.5.0

- Makefile
The publishing target was mounting the code at an incorrect location in the container, meaning it was using cached code for the publish.
This also fixes references to incorrect containers in the test targets.
> fix(ci): correct mount point for container

- Jenkinsfile
For Windows and macOS, a lot of parallel jobs can cause contention for resources and make the build slower.
> Combine Some Parallel Jobs

- Jenkinsfile
I always like to do a release build (as in something we're going to
release to the public) as a clean build, just to ensure that no issues
with caching creep in, but it's very slow to do both the prod and the
dev builds as clean. Even though we will release the dev builds to the
public, it seems an acceptable risk to not run this as a clean build.
> chore(ci): only clean for prod build

- safe-api/src/api/auth.rs
- safe-api/src/api/errors.rs
- safe-api/src/api/fake_scl.rs
- safe-api/src/api/fetch.rs
- safe-api/src/api/files.rs
- safe-api/src/api/helpers.rs
- safe-api/src/api/keys.rs
- safe-api/src/api/mod.rs
- safe-api/src/api/nrs.rs
- safe-api/src/api/nrs_map.rs
- safe-api/src/api/safe_client_libs.rs
- safe-api/src/api/safe_net.rs
- safe-api/src/api/wallet.rs
- safe-api/src/api/xorurl.rs
- safe-ffi/ffi/errors.rs
- safe-ffi/ffi/fetch.rs
Mostly this was a simple search/replace. This should reduce some verbosity.
Resolves #276
> refactor/error: rename ResultReturn to simply Result

- Cargo.lock
- safe-api/src/api/errors.rs
- safe-api/src/api/fake_scl.rs
- safe-api/src/api/nrs_map.rs
- safe-api/src/api/safe_client_libs.rs
- safe-api/src/api/safe_net.rs
- safe-api/src/api/wallet.rs
- safe-ffi/Cargo.toml
- safe-ffi/ffi/errors.rs
- safe-ffi/ffi/fetch.rs
- safe-ffi/lib.rs
This PR provides a nicer separation of concerns than previously. Now FFI-specific error codes do not appear outside the `ffi` module. The organization of the code is also simplified with respect to the Native and FFI error types.
Resolves #291
> refactor/ffi: move error codes to FFI Error

- Dockerfile.android.x86_64.build
This incorrect path was causing old source to be built because no matter where you mounted in the new source, it would still be using this old path, which has the cached code.
> fix(ci): use correct source path

- README.md
Resolves #319
I had followed instructions in README but got an error because instructions did not mention that a vault must first be started.   
This PR contains the missing instructions.
> Add instructions for starting a vault before creating account or login

- Cargo.lock
- resources/test-scripts/cli-tests
- resources/test-scripts/run-auth-daemon
- safe-api/src/api/auth.rs
- safe-api/src/api/authd_client_api.rs
- safe-authd/authd.rs
- safe-cli/Cargo.toml
- safe-cli/cli.rs
- safe-cli/operations/auth_and_connect.rs
- safe-cli/operations/auth_daemon.rs
- safe-cli/operations/fake_auth.rs
- safe-cli/shell.rs
- safe-cli/subcommands/auth.rs
- safe-cli/subcommands/mod.rs
This PR also implements more flexibility for finding the safe-authd executable:
- It allows the user to provide the path of the safe-authd executable with `$SAFE_AUTHD_PATH` env var.
- If `$SAFE_AUTHD_PATH` is not set, it searches for the safe-authd executable in `$PATH`
- ...if the safe-authd executalbe is not found in `$PATH` if then tries to find it under `./target/<debug/release>` path, unless `$CARGO_TARGET_DIR` env var was set in which it's then used
> feat(cli): allow to pass account creation/login details with env vars or config file

- .github/workflows/master.yml
- .github/workflows/pr.yml
- Cargo.lock
- Makefile
- resources/build-component.sh
- resources/build-container.sh
- resources/get_release_description.sh
- resources/package-deploy-artifacts.sh
- resources/retrieve-build-artifacts.sh
- resources/tag.sh
This transfers the build and release process from Jenkins to GitHub Actions. The entire process is replicated here, split into 2 workflows, PR and master.
The PR configuration will run the tests and build the mobile configurations. The master configuration will build everything, then deploy and publish. There are conditionals that check for the existence
of a version change message, as before. Since you have the same configuration for building mobile in both workflows, there's a lot of duplication here, but for now we're just accepting that as a limitation
of the Actions system.
This [release](https://github.com/jacderida/safe-cli/releases/tag/0.5.3) on my fork was done using Actions.
Due to an issue with rust_sodium, we are also missing macOS for the time being, but sodium should be …
> chore(ci): github actions for release process

- Jenkinsfile
- Makefile
- resources/build-cache.sh
- resources/build-component.sh
- resources/build-container.sh
- resources/retrieve-build-artifacts.sh
This strips Jenkins down to just running the macOS build.
[This](https://jenkins.maidsafe.net/blue/organizations/jenkins/pipeline-safe_api/detail/PR-334/6/pipeline) build has a deployment.
```
2019-11-21 17:20:30   36049996 safe-ffi-a77d0d5-apple-ios-dev.zip
2019-11-21 17:20:30    4009475 safe-cli-a77d0d5-x86_64-apple-darwin-dev.zip
2019-11-21 17:20:31    5330170 safe-ffi-a77d0d5-x86_64-apple-darwin-dev.zip
2019-11-21 17:20:32   34576691 safe-ffi-a77d0d5-apple-ios.zip
2019-11-21 17:20:32    5242358 safe-cli-a77d0d5-x86_64-apple-darwin.zip
2019-11-21 17:20:33    6250799 safe-ffi-a77d0d5-x86_64-apple-darwin.zip
```
> chore(ci): strip jenkins down to macOS

- Cargo.lock
- safe-cli/Cargo.toml
- safe-cli/cli.rs
- safe-cli/subcommands/cat.rs
- safe-cli/subcommands/dog.rs
- safe-cli/subcommands/files.rs
- safe-cli/subcommands/helpers.rs
- safe-cli/subcommands/keys.rs
- safe-cli/subcommands/mod.rs
- safe-cli/subcommands/nrs.rs
- safe-cli/subcommands/wallet.rs
- safe-cli/tests/cli_dog.rs
Adds additional --output options: jsonpretty and yaml, eg:
```
OPTIONS:
...
-o, --output <output_fmt>     Output data serialisation: [json, jsonpretty, yaml]
```
These serialization options make it much nicer to view structured data than raw/compact json, which remains the default.  All sub-commands use the new serialization options.  Some examples:
```
safe cat --output=jsonpretty safe://hnyynyiptjhhhzsicasjqhrdnmgu78bm4bcrj8o7q6qazai8sfj3kbt8nqbnc
[
"safe://hnyynyiptjhhhzsicasjqhrdnmgu78bm4bcrj8o7q6qazai8sfj3kbt8nqbnc",
{
"/auth_and_connect.rs": {
"created": "2019-11-21T08:41:23Z",
"link": "safe://hbyyyynrmkqs4tn3bm9y57b7xr6tqaoca9e3insb9frkcs814h5r663pcy",
"modified": "2019-11-21T08:41:23Z",
"size": "3546",
"type": "text/x-rust"
},
"/auth_daemon.rs": {
"created": …
```
> Pretty serialized output via --output 

- safe-cli/cli.rs
- safe-cli/subcommands/mod.rs
- safe-cli/subcommands/setup.rs
Addresses #73 for auto-completion of commands in a shell.
Supports shells:
bash, fish, zsh, powershell, elvish
The completions are automatically generated from the values in
structopt, so they stay current as the cli params change over time.
To use the completions, eg in bash:
safe --dump-completions=bash > /tmp/out && source /tmp/out
**Considerations**
1. --dump-completions works for me, but could be renamed to anything, eg --completions is shorter.
2. I didn't use a shortopt (yet).   Can add if wanted.
3. All the logic is contained in a single if statement.. I could move it into a function if desired.
4. Nothing is specific to safe-cli app.  If there is a common code shared between the apps under safe-api, then I could make/move a func into the common area to be called by each of them, …
> Implements --dump-shellcompletions

- safe-api/src/api/auth.rs
- safe-cli/operations/auth_and_connect.rs
- safe-ffi/ffi/mod.rs
**Changes:**
- Add `auth_app` function in the `safe-ffi.
- Rename `connect` to the `connect_app` as it was causing an issue when loading the native lib on iOS.
> Add auth_app in ffi and rename connect to connect_app 

- safe-cli/README.md
Running a safe command which includes a versioned URL on my machine
results in a `No matches for wildcard` error so I'm having to put the
URL in quotes. Maybe this is only macOS, or my specific shell, but
probably does no harm putting the examples in the readme into quotes
as that should work universally.
> docs(UserGuide): add quotes around safe urls with version numbers

- Cargo.lock
- safe-cli/Cargo.toml
- safe-cli/cli.rs
- safe-cli/subcommands/files.rs
- safe-cli/subcommands/helpers.rs
- safe-cli/subcommands/keys.rs
- safe-cli/subcommands/wallet.rs
This PR enables reading from stdin for `safe files add` when `-` is specified as the location.
Example:
```
$ cat Cargo.toml | safe files add - safe://hnyynyww1tcm4dyoqcqr1t44uewi93xkmrbfqiontba5qyoethb7eucoqsbnc/Cargo.from_stdin.toml
FilesContainer updated (version 2): "safe://hnyynyww1tcm4dyoqcqr1t44uewi93xkmrbfqiontba5qyoethb7eucoqsbnc?v=2"
+  /Cargo.from_stdin.toml  safe://hbyyyydeok89zis7f8ca4ed64men66yo8ochfj8pror43k1xrq5hcxkwyq
```
and we can verify the content is correct:
```
$ safe cat safe://hbyyyydeok89zis7f8ca4ed64men66yo8ochfj8pror43k1xrq5hcxkwyq | md5sum
45d45fe602da3e3ba9099ed9579c922a  -
$ md5sum Cargo.toml 
45d45fe602da3e3ba9099ed9579c922a  Cargo.toml
```
Using `-` to indicate read from stdin is a common unix convention, eg used by the cat command.  However it does …
> feat(cli): implemented `safe files add -` to read from stdin

- safe-api/src/api/fetch.rs
- safe-cli/tests/cli_cat.rs
> fix(fetch): Attempting to fetch felative asset from ID now fails.

- resources/get_release_description.sh
- safe-authd/update.rs
- safe-cli/README.md
- safe-cli/operations/auth_daemon.rs
This was not needed when extracting from a .tar.gz package, but it was missing for .zip packages.
We are now setting execution permissions after the binary was extracted regardless its
compression type, and we do it only on non-Windows platforms.
> fix(update): set execution permissions to binary after installed/updated

- safe-cli/Cargo.toml
- safe-cli/subcommands/files.rs
- safe-cli/subcommands/helpers.rs
- safe-cli/tests/cli_files.rs
- safe-cli/tests/common/mod.rs
This PR addresses #409. 
I added `safe files tree` subcommand, which displays output in same style as unix `tree` command, but without any color highlighting.  Serialized output is also available.
I included a flag `--flat` that causes the full tree to be displayed in a flat list, with full paths displayed as well as file details.  This was very easy to do because that is the format returned by files_container_get() API, so I just exposed it without any filtering.
Example output of `safe files tree`
```
$ safe files tree safe://hnyynysurwzoiudugs47d7fjx7hwg3i7ch1ryowdm7gpgj4538n1mwqukgbncsafe://hnyynysurwzoiudugs47d7fjx7hwg3i7ch1ryowdm7gpgj4538n1mwqukgbnc
├── another.md
├── noextension
├── subfolder
│   ├── sub2.md
│   └── subexists.md
└── test.md
$ safe files tree -o yaml …
```
> feat(cli): implements 'safe files tree' subcommand

- safe-cli/README.md
* adds docs for `files tree`
* improves bash setup oneliner to prevent duplicate lines in ~/.bashrc
* fix typo
> doc(README): document  'files tree' subcommand, improve bash setup oneliner

- resources/install.sh
- safe-cli/README.md
- safe-cli/subcommands/auth.rs
Tidy up CLI readme with some typos and clarifications.
Add two sections under auth login, one for passing credentials from a config file, and another for using environment variables to log in. Added some text the the `--help` for `safe auth login` to offer an example format for a credentials file.
This resolves #419
> docs/readme: clarify CLI readme commands and fix typos

- safe-api/src/api/app/fetch.rs
- safe-api/src/api/app/files.rs
- safe-cli/subcommands/files.rs
- safe-cli/subcommands/xorurl.rs
- safe-ffi/ffi/files.rs
This is to cover one aspect of RFC #60 on Rust safe-api: https://github.com/maidsafe/rfcs/blob/master/text/0060-enable-creating-and-modifying-of-filescontainers-within-the-safe-browser-environment/0060-enable-creating-and-modifying-of-filescontainers-within-the-safe-browser-environment.md
> feat(api): support for creation of empty FilesContainers with files_container_create API

- safe-cli/README.md
- safe-cli/operations/vault.rs
- safe-cli/subcommands/vault.rs
This depends on a feature in safe-vault (https://github.com/maidsafe/safe_vault/pull/954), therefore we need to merge it only when there is a safe-vault release published which supports the `--update-only` flag.
> feat(cli): implement a vault update command

- Cargo.lock
- resources/install.sh
- safe-api/Cargo.toml
- safe-api/src/api/app/fake_scl.rs
- safe-api/src/api/app/fetch.rs
- safe-api/src/api/app/files.rs
- safe-api/src/api/app/keys.rs
- safe-api/src/api/app/mod.rs
- safe-api/src/api/app/nrs.rs
- safe-api/src/api/app/safe_client_libs.rs
- safe-api/src/api/app/test_helpers.rs
- safe-api/src/api/app/wallet.rs
- safe-api/src/api/app/xorurl.rs
- safe-api/src/api/authd_client/authd_client_api.rs
This also fixes an issue found in client authd start API.
> refactor/api: refactor unit tests to return a Result and remove the use of unwrap from them

- Cargo.lock
- safe-ffi/Cargo.toml
- safe-ffi/ffi/errors.rs
- safe-ffi/ffi/ipc.rs
- safe-ffi/ffi/logging.rs
- safe-ffi/ffi/mod.rs
- safe-ffi/lib.rs
- safe-ffi/sample_log_file/log.toml
> feat/ffi: move logging API from safe_app to safe-ffi

- safe-ffi/ffi/mod.rs
> feat/ffi: expose set_config_dir_path and app_is_mock API

- .github/ISSUE_TEMPLATE.md
mentioning a rust version number only leaves us with a maintenance overhead & confusion when it's out of date. Better to state that users should be using latest stable version, which we always aim to work with.
> chore/template: remove specific rust version no from issue template

- .github/workflows/benchmark.yml
- safe-cli/Cargo.toml
- safe-cli/benches/keys.rs
- safe-cli/benches/put.rs
- safe-cli/benches/wallet.rs
Add consistent sample size and put a measurement limit on runs to prevent blocking CI
> ci/bench: Improve benchmarks.

- safe-api/src/api/app/fetch.rs
- safe-api/src/api/app/files.rs
- safe-api/src/api/app/keys.rs
- safe-api/src/api/app/nrs.rs
- safe-api/src/api/app/wallet.rs
- safe-api/src/api/app/xorurl.rs
- safe-cli/subcommands/cat.rs
- safe-cli/subcommands/dog.rs
- safe-cli/subcommands/files_get.rs
- safe-cli/subcommands/helpers.rs
- safe-cli/tests/cli_dog.rs
- safe-cli/tests/cli_wallet.rs
- safe-ffi/ffi/fetch.rs
- safe-ffi/ffi/ffi_structs.rs
Also, adapt the dog command to show every step in the resolution chain, and resolves #518 
Example `dog` command output with a long URL resolution chain:
```
$ safe dog safe://subfile
== URL resolution step 1 ==
= NRS Map Container =
PublicName: "subfile"
XOR-URL: safe://subfile
Version: 0
Type tag: 1500
XOR name: 0xaaebb5968b8eabdda8f9185cfca60198861b12a370b63bc5799edd7ce0bca2c3
Native data type: PublishedSeqAppendOnlyData
+------------------+----------------------+----------------------+------------------------------+
| NRS name/subname | Created              | Modified             | Link                         |
+------------------+----------------------+----------------------+------------------------------+
| subfile          | 2020-05-06T04:38:30Z | 2020-05-06T04:38:30Z | …
```
> feat/api: make the `inspect` API to return the complete URL resolution chain

- .github/workflows/network-test.yml
- safe-api/src/api/app/fetch.rs
- safe-api/src/api/app/nrs.rs
- safe-authd/operations.rs
- safe-cli/subcommands/dog.rs
- safe-cli/subcommands/files.rs
- safe-cli/subcommands/files_get.rs
- safe-cli/tests/cli_files_get.rs
- safe-cmd-test-utilities/src/lib.rs
- safe-ffi/ffi/fetch.rs
- safe-ffi/ffi/ffi_structs.rs
- safe-ffi/ffi/nrs.rs
A refactoring is also made here to:
- Remove URL resolution redundant logic from CLI in favor of using the `fetch` API
- Remove the `parse_and_resolve_url` from being part of the public API and keeping it only as an internal helper function
- Disabling CI tests with mini-network as there is a known issue in SCL which causes them to fail
> fix/cli: files get was not resolving URLs with more than one resolution step and paths

- safe-api/src/api/app/consts.rs
- safe-api/src/api/app/fetch.rs
- safe-api/src/api/app/files.rs
- safe-api/src/api/app/helpers.rs
- safe-cli/subcommands/cat.rs
- safe-cli/subcommands/files.rs
- safe-cli/subcommands/files_get.rs
- safe-cli/tests/cli_cat.rs
- safe-cli/tests/cli_files.rs
- safe-cli/tests/cli_files_get.rs
- safe-cli/tests/cli_xorurl.rs
This PR enables support for PUT/GET of empty directories.
Until now, each FileItem in a FilesMap has represented a file.  Directories did not exist as their own entity, but rather were computed from file paths.   This strategy fails for empty directories because there is no file inside the directory, thus the directory is not included in any FileItem path.
This PR changes the scheme such that a FileItem may be a File, Directory, or Symlink.  The type is identified by the pre-existing "type" metadata field, which holds mime types.  So now, inode/directory --> Dir,  inode/symlink --> Symlink, anything else --> File.  This means that directories now have metadata such as created, modified, just like files do.
Some additonal metadata fields are also added, if available on local platform, …
> support empty directories and lays groundwork for symlinks and hidden files.

- safe-api/src/api/app/files.rs
- safe-cli/tests/cli_files.rs
- safe-cli/tests/cli_xorurl.rs
Changes in this PR:
1. removes the filter for files/dirs beginning with `.` when performing PUT or SYNC
2. omits sub-directories from PUT or SYNC if recursive flag not present.  (prevents empty sub-dirs)
3. updates tests to expect the above changes.
Rationale for 1:
* The check for files beginning with `.` is a platform specific (unix) method to identify hidden files and filter them out.  However, hidden files work differently on windows, so arguably this check wasn't even accomplishing its purpose on that platform, and possibly others.
* As far as I can see, there is no valid reason to filter hidden files in mandatory fashion.  It would definitely surprise users that are familiar with cp, scp, or rsync, as these tools do not do this.
* Decisions about this kind of filtering should be …
> feat(cli): put/sync includes "hidden" files, and omit sub-dirs if not recursive.

- safe-api/src/api/app/fetch.rs
- safe-cli/subcommands/files.rs
- safe-cli/tests/cli_files.rs
- safe-cmd-test-utilities/src/lib.rs
This PR contains a fix for #510, specifically for `files ls`, as `files tree` was already addressed.
Changes:
* `files ls` now uses Safe::inspect() api to resolve URLs.
* added optimization to filter_files_map() for single-file case, which can do a simple path lookup.
* added/moved/changed test cases:
- calling_files_ls_on_nrs_with_path()
- calling_files_ls_on_single_file
- calling_files_ls_with_invalid_path()
* adds safe_cmd() to safe-cmd-test-utilities, a succinct way to exec, check exit code, and get all command output.
@bochaco please have a look at the changes in files.rs for `Ls` subcommand.  I had a lot of difficulty trying to get it to work for a single file path using the Safe::fetch() API, so I came up with an alternate solution using Safe::inspect().  I commented what it is …
> fix(cli): addresses issue 510. 'files ls' now uses nrs paths

- .github/workflows/benchmark.yml
- .github/workflows/master.yml
- .github/workflows/network-test.yml
- .github/workflows/pr.yml
Code coverage is gathered through the cargo tarpaulin GHA and pushed to coveralls.io via the coveralls GHA.
Note that at this time the code coverage is only for the safe-api crate with `--features=scl-mock`, it excludes the other crates and features at this time. I have been investigating uploading an aggregated code coverage figure for safe-api and safe-cli, with multiple features, but I've hit multiple obstacles along the way so will need to return to that later.
Example on my fork of the code coverage stats being generated by CI successfully from this PR branch can be seen [here](https://github.com/S-Coyle/safe-api/runs/734970689?check_suite_focus=true). This has then been uploaded to my coveralls.io page [here](https://coveralls.io/github/S-Coyle/safe-api).
Also added a refactor …
> Add safe api code coverage and refactor GHA CI files

- .github/workflows/pr.yml
Resolves an issue with tests failing on Windows due to symlinks not being checked out properly.
> chore(ci): set git to checkout symlinks on Windows

- Makefile
This commit was originally part of #592 but separating it out to unblock it
At the moment the release uploads all contain version numbers - this is
fine, but for CI purposes it would also be useful to have an additional file
with `latest` instead of a version number, so CI can point to it and not
be required to be manually updated after every release.
Example of where this will be used by SCL [here](https://github.com/maidsafe/safe-client-libs/pull/1224#issuecomment-655957414) and [here](https://github.com/maidsafe/safe-client-libs/pull/1229/files).
Note that a safe-ffi `latest` will be created, though it is not used anywhere at the moment. Thought it better to add anyway to be consistent.
> On version change upload `latest` zips and tars to S3

- Cargo.lock
- safe-cli/Cargo.toml
- safe-cli/operations/vault.rs
launch tool was updated today [here](https://github.com/maidsafe/sn_launch_tool/pull/19/commits/3d826d4f8a3c7a0d19d0aa0a1463f688c622159b).
This PR updates all references to it (both to `safe-nlt` and `safe-network-launch-tool`) to match the new name
> chore(deps): update to use renamed sn_launch_tool dependency

- resources/install.sh
Version numbers now contain a v, e.g. `v0.15.0` so script not
expecting this. added a sed to strip out the v
> chore(install): update script to account for `v` in version no

- resources/install.sh
Reports on the forum that install script wasn't working on macOS. Updated the grep & tested on macOS & Ubuntu to make sure this change works fine. Don't have access to Windows at the moment.
> fix(install): fix install script version grep cmd

- .github/workflows/benchmark.yml
- .github/workflows/master.yml
- .github/workflows/network-test.yml
- .github/workflows/pr.yml
- .github/workflows/security_audit.yml
- sn_authd/Cargo.toml
- sn_authd/main.rs
- sn_authd/requests/status.rs
- sn_authd/update.rs
- sn_cli/Cargo.toml
- sn_cli/main.rs
- sn_cli/operations/auth_daemon.rs
- sn_cli/operations/config.rs
- sn_cli/operations/helpers.rs
- sn_cli/operations/node.rs
- sn_cli/subcommands/update.rs
Normally nothing changes for Maidsafe build process because self-update is an opt-out feature.
The procedure is a little more complex for user wanting to disable self-update feature:
```bash
cargo build -p sn_api --release
cd sn_cli/
cargo build --release --no-default-features --features "simulated-payouts"
cd ../sn_authd/
cargo build --release --no-default-features --features "simulated-payouts"
cd ..
```
Another possibility is to edit Cargo.toml file in sn_authd and sn_cli directories and remove self-update from default feature list:
```diff
sn_authd/Cargo.toml:
[features]
-default = ["simulated-payouts", "self-update"]
+default = ["simulated-payouts"]
simulated-payouts = ["sn_api/simulated-payouts"]
self-update = ["self_update"]
sn_cli/Cargo.toml:
[features]
-default = …
```
> Control self_update by a cargo feature

- .github/workflows/master.yml
- resources/get_release_description.sh
- resources/install.sh
- sn_cli/README.md
Currently building gnu binary for Linux, switching to musl for greater compatibility.
Note that `install.sh` on S3 will need updated accordingly once a release with this code is triggered.
> chore(cicd): update CI/CD to produce musl binary

- .github/workflows/benchmark.yml
- .github/workflows/master.yml
- .github/workflows/network-test.yml
- .github/workflows/pr.yml
- .github/workflows/security_audit.yml
- Cargo.lock
E.g. vx.x.x
This is what is expected by the install script, and it keeps this repo inline with others.
> Add `v` to generated tag and other CI maintenance

- sn_api/src/api/app/xorurl.rs
This is already done by Url::parse in host.rs#L96
https://github.com/servo/rust-url/blob/31bc0da54c659094dacb1434996f10ed1b46b5ae/url/src/host.rs#L96
which throws the error on host.rs#L113
Note the removed error message does not appear in any existing tests.
> Remove unused check for whitespace

- sn_cli/subcommands/node.rs
Running `cargo run` yielded the following:
```
thread 'main' panicked at 'Argument short must be unique
-n is already in use', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/parser.rs:193:13
```
Apparently the node subcommand was using `-n` (for number of nodes) as well as the global command (for dry running). I've solved it by omitting the short option in the node subcommand.
> fix: remove short option used for dry run

- Cargo.lock
- sn_api/Cargo.toml
- sn_api/src/api/app/xorurl.rs
- sn_api/src/api/authenticator/mod.rs
- sn_cli/Cargo.toml
- sn_cmd_test_utilities/Cargo.toml
- sn_cmd_test_utilities/src/lib.rs
In sn_api the majority of dependencies use tiny-keccak 2.0.2 so it makes sense to have them all at the same version.
```
sn_api (master) $  cargo tree -i tiny-keccak:1.5.0
tiny-keccak v1.5.0
├── self_encryption v0.19.8
│   └── sn_client v0.46.2
│       └── sn_api v0.18.0 (/tmp/sn_api/sn_api)
│           ├── sn_authd v0.1.0 (/tmp/sn_api/sn_authd)
│           ├── sn_cli v0.18.0 (/tmp/sn_api/sn_cli)
│           └── sn_cmd_test_utilities v1.0.0 (/tmp/sn_api/sn_cmd_test_utilities)
│               [dev-dependencies]
│               └── sn_cli v0.18.0 (/tmp/sn_api/sn_cli)
├── sn_api v0.18.0 (/tmp/sn_api/sn_api) (*)
├── sn_client v0.46.2 (*)
├── sn_cmd_test_utilities v1.0.0 (/tmp/sn_api/sn_cmd_test_utilities) (*)
└── sn_data_types v0.14.3
├── sn_api v0.18.0 (/tmp/sn_api/sn_api) (*)
├── sn_client …
```
> Update tiny-keccak from 1.5.0 to 2.0.2

- sn_authd/update.rs
- sn_cli/operations/helpers.rs
> chore(clippy): adds clippy exception for unused result on windows

- sn_cli/operations/node.rs
- sn_cli/subcommands/auth.rs
- sn_cli/subcommands/mod.rs
- sn_cli/subcommands/node.rs
Fixes #611 
See forum thread [here](https://forum.safedev.org/t/what-can-i-do-to-help/2965) for discussion, but it doesn't "fix" the behavior as might be suggested in the git issue.
The idea is that subcommands in our binary aren't versioned explicitly, so this patch removes the `-V` option when subcommands are supplied to avoid confusion between subcommand version (which we don't really support) and the version of external binaries like `sn_node`. Then this also adds a `bin-version` subcommand to `node` and `auth` to fetch the version of the external binary, so that the semantics are clearer as well as the distinction between the `cli` version and `sn_node` and `sn_authd` versions.
> refactor: Adds bin-version subcommand to node & auth, removes -V for subcommands

- qjsonrpc/src/jsonrpc.rs
- qjsonrpc/src/lib.rs
Closes #730 
This patch would expose several useful spec-defined error codes in the `qjsonrpc` crate.
> feat(jsonrpc): adds spec-defined error code constants

- Cargo.lock
- sn_api/Cargo.toml
- sn_api/src/api/app/files/mod.rs
- sn_api/src/api/app/nrs.rs
- sn_api/src/api/app/safe_client.rs
- sn_api/src/api/common.rs
- sn_api/src/api/mod.rs
Currently FilesContainers and NRSContainers store its metadata as entries in the Sequence CRDT-based data type. This PR changes that making sure all metadata is stored on Blobs and only link/s are kept in the Sequence data type.
> feat(api): changing the way FilesContainers and NRSContainers data is stored on the network

- .github/workflows/network-test.yml
- resources/test-scripts/api-tests
- sn_api/src/api/app/fetch.rs
- sn_api/src/api/app/keys.rs
- sn_api/src/api/app/mod.rs
- sn_api/src/api/app/safe_client.rs
- sn_api/src/api/app/sequence.rs
- sn_api/src/api/app/test_helpers.rs
- sn_api/src/api/app/wallet.rs
- sn_api/src/api/app/xorurl.rs
This re-enables running sn_api tests in CI, but here only a first subset of all tests is enabled, those for the following APIs:
- fetch
- sequence
- xorurl
- keys
- wallet
Also, one wallet tests is being for now skipped as there seems to be a bug in the network for Map inserts, which will be investigated and when fixed this test can be enabled too.
> chore(ci): re-enabling sn_api tests in CI

- sn_cli/README.md
Testing has shown that without the VS C++ redistribution package installed we get the error `error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory`
> docs(cli): add visual c++ libs to windows requirements

- sn_cli/README.md
Having readme examples point to the correct location should help avoid any confusion
> docs(readme): update cli readme s3 node config location

- sn_cli/Cargo.toml
- sn_cli/main.rs
[module_path] level time [file:line] args
See
https://github.com/maidsafe/sn_node/blob/de12c4d36c63451ed5283d98d0989fcac224b937/src/utils.rs#L60-L76
for matching sn_node log format
I appreciate the cli logs form part of the user experience so this format may not suit the desired ux. My reason for the pull request is so node logs and cli logs can both be parsed the same way by a log visualizer.
> feat(cli): log format matches sn_node log format

- sn_api/src/api/app/keys.rs
- sn_api/src/api/app/wallet.rs
- sn_cli/subcommands/keys.rs
Prevent unnecessary cloning (which SecretKey doesn't even allow) to pass SecretKey to get balance from key.
> feat: pass SecretKey by reference

- sn_cli/README.md
- sn_cli/subcommands/networks.rs
```
safe networks switch fleming-testnet
Switching to 'fleming-testnet' network...
Fetching 'fleming-testnet' network connection information from 'https://sn-node.s3.eu-west-2.amazonaws.com/config/node_connection_info.config' ...
Successfully switched to 'fleming-testnet' network in your system!
If you need write access to the 'fleming-testnet' network, you'll need to restart authd, unlock a Safe and re-authorise the CLI again
```
(added  **safe auth restart**) 
Why? 
New starters don't know how to do that. .
```
safe networks switch fleming-testnet
Switching to 'fleming-testnet' network...
Fetching 'fleming-testnet' network connection information from 'https://sn-node.s3.eu-west-2.amazonaws.com/config/node_connection_info.config' ...
Successfully switched to 'fleming-testnet' network in …
```
> enhance cli doc, how to safe auth restart

- sn_api/src/api/app/fetch.rs
- sn_api/src/api/app/files/mod.rs
- sn_api/src/api/app/keys.rs
- sn_api/src/api/app/nrs/mod.rs
- sn_api/src/api/app/safe_client.rs
- sn_api/src/api/app/sequence.rs
- sn_api/src/api/app/wallet.rs
Tweaked a few method signatures to leave out the mutability binding.
This means there can be multiple (immutable) references, instead of
one unique reference to the Safe instance.
(This is more of a question of whether this is something we want. I do not think there is a reason to have this being mutable, but if so, then this PR is also a commitment to the future to keep the API such that the instance can be borrowed immutably and therefore there can be multiple references at the same time. This might allow for easier usage in async contexts. This PR might serve as a draft to make sure as much of the API as possible aligns with these changes I've made mainly in keys.rs.)
> feat: allow aliases of Safe (immutable references)

- src/app/test_helpers.rs
This is an attempt to fix the hanging tests that use the retry_loop! macro which loops indefinitely, making tests hang and hiding the repeating error.
This is my proposal for a fix: it retries a given number of times (defaults to 10 if n is not provided) and bails after retrying those n times.
Along with small style improvements in test helpers.
> Retry loopn

- README.md
BREAKING CHANGE: the actual breaking changes were in the previous PR and commits. This change simply just modifies the README so we can get a new release through.
The 0.34.2 release will be yanked from crates.io.
> chore: use readme change to force new release
